// models/modelConfig.mjs

import ClientModel from "./clients.mjs";

export const models = {
  WMMModel: () => import("./wmm.mjs"),
  HRGModel: () => import("./hrg.mjs"),
  FOMModel: () => import("./fom.mjs"),
  CALModel: () => import("./cal.mjs"),
  GroupModel: () => import("./groups.mjs"),
  ComplimentaryModel: () => import("./complimentary.mjs"),
  PromoModel: () => import("./promo.mjs"), // Add PromoModel import
};

export const modelConfigs = {
  WMMModel: {
    projectFields: {
      clientid: 1,
      subsdate: 1,
      enddate: 1,
      renewdate: 1,
      subsyear: 1,
      copies: 1,
      subsclass: 1,
      remarks: 1,
      paymtref: 1,
      paymtamt: 1,
      paymtmasses: 1,
      calendar: 1,
      donorid: 1,
      adddate: 1,
    },
    groupFields: {
      subsdate: "$subsdate",
      enddate: "$enddate",
      renewdate: "$renewdate",
      subsyear: "$subsyear",
      copies: "$copies",
      subsclass: "$subsclass",
      remarks: "$remarks",
      paymtref: "$paymtref",
      paymtamt: "$paymtamt",
      paymtmasses: "$paymtmasses",
      calendar: "$calendar",
      donorid: "$donorid",
      adddate: "$adddate",
    },
  },
  HRGModel: {
    projectFields: {
      clientid: 1,
      recvdate: 1,
      renewdate: 1,
      campaigndate: 1,
      paymtref: 1,
      paymtamt: 1,
      remarks: 1,
      unsubscribe: 1,
    },
    groupFields: {
      recvdate: "$recvdate",
      renewdate: "$renewdate",
      campaigndate: "$campaigndate",
      paymtref: "$paymtref",
      paymtamt: "$paymtamt",
      remarks: "$remarks",
      unsubscribe: "$unsubscribe",
    },
  },
  FOMModel: {
    projectFields: {
      clientid: 1,
      recvdate: 1,
      remarks: 1,
      paymtref: 1,
      paymtamt: 1,
      paymtform: 1,
      unsubscribe: 1,
      adddate: 1,
      adduser: 1,
    },
    groupFields: {
      recvdate: "$recvdate",
      paymtref: "$paymtref",
      paymtamt: "$paymtamt",
      paymtform: "$paymtform",
      remarks: "$remarks",
      unsubscribe: "$unsubscribe",
      adddate: "$adddate",
      adduser: "$adduser",
    },
  },
  CALModel: {
    projectFields: {
      clientid: 1,
      recvdate: 1,
      caltype: 1,
      calqty: 1,
      calamt: 1,
      paymtref: 1,
      paymtamt: 1,
      paymtform: 1,
      paymtdate: 1,
      remarks: 1,
      adddate: 1,
      adduser: 1,
    },
    groupFields: {
      recvdate: "$recvdate",
      caltype: "$caltype",
      calqty: "$calqty",
      calamt: "$calamt",
      paymtref: "$paymtref",
      paymtamt: "$paymtamt",
      paymtform: "$paymtform",
      paymtdate: "$paymtdate",
      remarks: "$remarks",
      adddate: "$adddate",
      adduser: "$adduser",
    },
  },
  GroupModel: {
    projectFields: {
      id: 1,
      name: 1,
      description: 1,
    },
    groupFields: {
      id: "$id",
      name: "$name",
      description: "$description",
    },
  },
  ComplimentaryModel: {
    projectFields: {
      clientid: 1,
      subsdate: 1,
      enddate: 1,
      subsyear: 1,
      copies: 1,
      remarks: 1,
      calendar: 1,
      adddate: 1,
      adduser: 1,
    },
    groupFields: {
      subsdate: "$subsdate",
      enddate: "$enddate",
      subsyear: "$subsyear",
      copies: "$copies",
      remarks: "$remarks",
      calendar: "$calendar",
      adddate: "$adddate",
      adduser: "$adduser",
    },
  },
  PromoModel: {
    projectFields: {
      clientid: 1,
      subsdate: 1,
      enddate: 1,
      subsyear: 1,
      copies: 1,
      remarks: 1,
      calendar: 1,
      referralid: 1,
      adddate: 1,
      adduser: 1,
    },
    groupFields: {
      subsdate: "$subsdate",
      enddate: "$enddate",
      subsyear: "$subsyear",
      copies: "$copies",
      remarks: "$remarks",
      calendar: "$calendar",
      referralid: "$referralid",
      adddate: "$adddate",
      adduser: "$adduser",
    },
  },
};

export const clientFields =
  "id lname fname mname sname title bdate company address street city barangay zipcode area acode contactnos cellno ofcno email type group remarks adddate adduser metadata";

export { ClientModel };
